# Guía de ejercicios Pandas DataFrame

En esta guía utilizaremos el siguiente dataset [SF Salaries Dataset](https://www.kaggle.com/kaggle/sf-salaries) extraido desde Kaggle (kaggle.com). Complete cada uno de los ejercicios:

#### 1. Importe la librería pandas con el alias pd

In [2]:
import pandas as pd

#### 2. Lea el siguiente archivo https://patricioaraneda.cl/public/Salaries.csv y almacénelo en una variable (nómbrela "sal")
Asegúrese que cuenta con el archivo y se encuentra en la misma carpeta que este notebook.

In [3]:
data = pd.read_csv('https://patricioaraneda.cl/public/Salaries.csv')

#### 3. Despliegue los primeros 4 registros de los datos

In [21]:
data.sample(10)

,Id,EmployeeName,JobTitle,BasePay,OvertimePay,OtherPay,Benefits,TotalPay,TotalPayBenefits,Year,Notes,Agency,Status,Taxes
81652,81653,Roselle D Ferrer,Senior Water Service Inspector,101723.47,2710.97,8932.79,34363.87,113367.23,147731.10,2013,NaN,San Francisco,NaN,10172.347
83663,83664,Jose G Calvo-Perez,Police Officer,91917.39,7274.51,3613.22,32389.62,102805.12,135194.74,2013,NaN,San Francisco,NaN,9191.739
39904,39905,Robert Dufresne,Transit Operator,71251.23,56238.12,9401.86,44850.59,136891.21,181741.80,2012,NaN,San Francisco,NaN,7125.123
13010,13011,CONNIE CHAN,ADMINISTRATIVE SERVICES MANAGER,84783.37,0.00,0.00,NaN,84783.37,84783.37,2011,NaN,San Francisco,NaN,8478.337
29020,29021,HUI XIAN ZHAO,PORTER,21644.50,0.00,642.95,NaN,22287.45,22287.45,2011,NaN,San Francisco,NaN,2164.450
134015,134016,Clarence M Dalton,Custodian,54703.00,3185.40,624.00,26651.90,58512.40,85164.30,2014,NaN,San Francisco,NaN,5470.300
57145,57146,Kamson Chan,Transit Operator,65380.02,2344.82,749.02,23049.59,68473.86,91523.45,2012,NaN,San Francisco,NaN,6538.002
116493,116494,James I Whipple,Senior Building Inspector,120350.05,1076.70,6017.55,40854.39,127444.30,168298.69,2014,NaN,San Francisco,NaN,12035.005
104789,104790,Cula A Clark,Patient Care Assistant,14726.79,0.00,376.25,0.00,15103.04,15103.04,2013,NaN,San Francisco,NaN,1472.679
118368,118369,Carolyn A Welch,Pr Administrative Analyst,114317.03,0.00,0.00,39423.56,114317.03,153740.59,2014,NaN,San Francisco,NaN,11431.703

In [4]:
data.head(4)

,Id,EmployeeName,JobTitle,BasePay,OvertimePay,OtherPay,Benefits,TotalPay,TotalPayBenefits,Year,Notes,Agency,Status
0,1,NATHANIEL FORD,GENERAL MANAGER-METROPOLITAN TRANSIT AUTHORITY,167411.18,0.00,400184.25,NaN,567595.43,567595.43,2011,NaN,San Francisco,NaN
1,2,GARY JIMENEZ,CAPTAIN III (POLICE DEPARTMENT),155966.02,245131.88,137811.38,NaN,538909.28,538909.28,2011,NaN,San Francisco,NaN
2,3,ALBERT PARDINI,CAPTAIN III (POLICE DEPARTMENT),212739.13,106088.18,16452.60,NaN,335279.91,335279.91,2011,NaN,San Francisco,NaN
3,4,CHRISTOPHER CHONG,WIRE ROPE CABLE MAINTENANCE MECHANIC,77916.00,56120.71,198306.90,NaN,332343.61,332343.61,2011,NaN,San Francisco,NaN

#### 4. Despliegue los últimos 2 registros del set de datos

In [5]:
data.tail(2)

,Id,EmployeeName,JobTitle,BasePay,OvertimePay,OtherPay,Benefits,TotalPay,TotalPayBenefits,Year,Notes,Agency,Status
148652,148653,Not provided,Not provided,NaN,NaN,NaN,NaN,0.00,0.00,2014,NaN,San Francisco,NaN
148653,148654,Joe Lopez,"Counselor, Log Cabin Ranch",0.0,0.0,-618.13,0.0,-618.13,-618.13,2014,NaN,San Francisco,NaN

#### 5. Utilice el método .info() para ver cuántos registros tiene el set de datos

#### 6. Utilice el método .describe() para obtener estadísticas rápidas del set de datos

#### 7. ¿Cuál es el monto del sueldo base más alto? (BasePay)

In [6]:
data['BasePay'].max()

np.float64(319275.01)

#### 8. ¿Cuál es la mediana del sueldo base?

In [7]:
data['BasePay'].median()

np.float64(65007.45)

#### 9. ¿Cuál es la media del sueldo base?

In [8]:
data['BasePay'].mean()

np.float64(66325.44884048769)

#### 10. ¿Cuánto fue el monto de sueldo base (BasePay) más alto del año 2013?

In [9]:
data[data['Year'] == 2013]['BasePay'].max()

np.float64(319275.01)

#### 11. ¿A cuántas personas se les paga tiempo extra? (OvertimePay)

In [ ]:
# la condicion evalua true o false, y luego sum() suma los valores true, que son equivalentes a 1
(data['OvertimePay'] > 0).sum()

np.int64(71328)

In [ ]:
(data['OvertimePay'] > 0).sum()

#### 12. ¿Cuál es el cargo de JOSEPH DRISCOLL?
**Nota**: Use mayúsculas (también hay un Joseph Driscoll con minúsculas)

In [11]:
data[data['EmployeeName'] == 'JOSEPH DRISCOLL']['JobTitle'].values[0]

'CAPTAIN, FIRE SUPPRESSION'

#### 13. ¿Cuál es el sueldo total de JOSEPH DRISCOLL incluyendo beneficios?

In [12]:
data[data['EmployeeName'] == 'JOSEPH DRISCOLL']['TotalPayBenefits'].values[0]

np.float64(270324.91)

#### 14. ¿Cuál es el nombre de la persona mejor pagada? (beneficios incluidos)

In [13]:
data.loc[data['TotalPayBenefits'].idxmax(), 'EmployeeName']

'NATHANIEL FORD'

#### 15. ¿Cuál es el nombre de persona peor pagada (beneficios incluidos)?

In [14]:
data.loc[data['TotalPayBenefits'].idxmin(), 'EmployeeName']

'Joe Lopez'

#### 16. Agregue una columna que se llame 'Taxes' y que corresponda al 10% del sueldo base

In [15]:
data['Taxes'] = data['BasePay'] * 0.10

#### 17. ¿Cuánto fue la recaudación de impuestos en el año 2013?

In [16]:
data[data['Year'] == 2013]['Taxes'].sum()

np.float64(257638074.80400002)

#### 18. Desafío: calcule el promedio del 10% de sueldos más altos (BasePay)

In [17]:
data['BasePay'].dropna().nlargest(int(len(data) * 0.10)).mean()

np.float64(145160.43789640092)

#### 19. Calcule el promedio del 10% de sueldos más bajos (BasePay)

In [18]:
data['BasePay'].dropna().nsmallest(int(len(data) * 0.10)).mean()

np.float64(2742.6652929700645)